<?php
// Session check (optional if needed for this page)
session_start();
$timeout_duration = 1800;
if (
  !isset($_SESSION['uid']) || !isset($_SESSION['logged_in']) || (time() - $_SESSION['login_time'] > $timeout_duration)
) {
  session_unset();
  session_destroy();
  header("Location: attendance_login.php?message=Session expired");
  exit();
}

// Refresh session time
$_SESSION['login_time'] = time();

// Receive GET parameters
$branch = $_GET['branch'] ?? 'N/A';
$year = $_GET['year'] ?? 'N/A';
$section = $_GET['section'] ?? 'N/A';
$from_date = $_GET['from_date'] ?? '';
$to_date = $_GET['to_date'] ?? '';
?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Vignan Student Attendance Portal</title>
</head>

<body style="font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #f0f4f8;">
  <div
    style="text-align: center; background-color: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
    <img src="vignan logo.png" alt="College Logo" width="80">
    <h1 style="color: #d62828; margin: 10px 0;">VIGNAN INSTITUTE OF TECHNOLOGY AND SCIENCE</h1>
    <p style="margin: 5px 0;">Near Ramoji Film City, Deshmukhi Village, Pochampally Mandal, Yadadri Bhuvanagiri Dist.
    </p>
    <p style="color: #023047; font-weight: bold; margin: 5px 0;">(Approved by AICTE, New Delhi, Affiliated to JNTUH,
      Hyderabad)</p>
    <h3 style="color: #d62828; margin: 5px 0;">AN AUTONOMOUS INSTITUTION</h3>
    <div
      style="position: absolute; top: 20px; right: 30px; border: 2px solid #888; padding: 10px; font-weight: bold; border-radius: 5px; background-color: #fefefe;">
      <p style="margin: 0;">Eamcet Code<br><span style="color: #d62828;">VGNT</span><br>Dist Code: <span
          style="color: #1d3557;">YBG</span></p>
    </div>
  </div>

  <div style="text-align: center; margin-top: 30px;">
    <h2 style="color: #264653;">Vignan Student Attendance Portal</h2>
    <h3>Class Attendance Report - AY 2024-25 I Sem.</h3>
    <p><strong>Branch:</strong> <?= htmlspecialchars($branch) ?>&nbsp;&nbsp;&nbsp;
      <strong>Year:</strong> <?= htmlspecialchars($year) ?>&nbsp;&nbsp;&nbsp;
      <strong>Sec:</strong> <?= htmlspecialchars($section) ?>
    </p>
    <p><strong>From:</strong> <?= htmlspecialchars($from_date) ?>&nbsp;&nbsp;&nbsp;
      <strong>To:</strong> <?= htmlspecialchars($to_date) ?>
    </p>
  </div>

  <div style="overflow-x: auto; margin-top: 30px;">
    <table border="1" cellspacing="0" cellpadding="5"
      style="width: 100%; border-collapse: collapse; background-color: white; font-size: 14px;">
      <thead style="background-color: #e63946; color: white;">
        <tr>
          <th rowspan="2">S.No.</th>
          <th rowspan="2">H.T No.</th>
          <th rowspan="2">Student Name</th>
          <th colspan="11">Number of Hours Conducted</th>
          <th rowspan="2">CRT</th>
          <th rowspan="2">Total</th>
          <th rowspan="2">Percentage (%)</th>
        </tr>
        <tr style="background-color: #f77f00; color: white;">
          <th>DM</th>
          <th>BEFA</th>
          <th>OS</th>
          <th>DBMS</th>
          <th>SE</th>
          <th>OS LAB</th>
          <th>DBMS LAB</th>
          <th>NODE JS</th>
          <th>COI</th>
          <th>REAL TIME PROJECT</th>
        </tr>
      </thead>
      <tbody>
        <!-- Dynamic attendance data rows will go here -->
      </tbody>
    </table>
  </div>

  <div style="text-align: center; margin-top: 50px; font-size: 13px; color: #555;">
    <p>Generated by Vignan Attendance System</p>
  </div>
</body>

</html>